#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 17 16:07:05 2018

@author: lydiayu
"""
"""
n_str = "007"
sum = 0
for i in range(len(n_str)):
    sum += int(n_str[i])
    
print(sum)
"""

base = 3
num = 12
exponent = 0
while base**exponent <= num:
    exponent += 1
    
print(exponent)